AllCops:
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'spec/dummy/db/**/*'
    - 'spec/dummy/log/**/*'
    - 'spec/dummy/tmp/**/*'
    - 'spec/dummy/config/puma.rb'
    - 'spec/dummy/config/environments/test.rb'
    - 'spec/dummy/bin/bundle'
  TargetRubyVersion: 2.4

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120


Style/FormatStringToken:
  Enabled: false