name: Ruby

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
        bundler-cache: true
    - name: Run the default task
      run: |
        RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load
        RAILS_ENV=test bundle exec rspec
